<?php
if ( ! defined( 'ABSPATH' ) ) exit;

// Category slugs => display names
$bartle_categories = [
    'explorer'   => 'Explorer (Discovery)',
    'achiever'   => 'Achiever (Achievement)',
    'socializer' => 'Socializer (Social)',
    'strategist' => 'Strategist (Competition)',
];

$bartle_descriptions = [
    'explorer'   => 'You are motivated by exploring new systems, discovering hidden knowledge, and the thrill of the unknown.',
    'achiever'   => 'You are motivated by setting and achieving measurable goals, tracking progress, and mastering skills.',
    'socializer' => 'You are motivated by interacting with others, building relationships, and contributing to a community.',
    'strategist' => 'You are motivated by competition, overcoming challenges, and proving your skills against others.',
];

$bartle_questions = [
    'teen' => [
        'explorer' => [
            ['text' => 'I enjoy diving into new systems or tools just to see how they work.', 'reverse' => false],
            ['text' => 'I’d rather explore a new idea than stick with what I already know.', 'reverse' => false],
            ['text' => 'I often get lost in rabbit holes of curiosity.', 'reverse' => false],
            ['text' => 'I try new processes or strategies even when the old ones still work.', 'reverse' => false],
            ['text' => 'I value learning for its own sake.', 'reverse' => false],
            ['text' => 'I enjoy being surprised by something I didn’t expect.', 'reverse' => false],
            ['text' => 'I like being the first to discover something new in my school or hobby.', 'reverse' => false],
            ['text' => 'I often research things deeply even if I don’t need to.', 'reverse' => false],
            ['text' => 'I avoid experimenting if it means risking failure.', 'reverse' => true],
            ['text' => 'I’d rather stick to what’s familiar than explore something unknown.', 'reverse' => true],
        ],
        'achiever' => [
            ['text' => 'I set measurable goals for myself in school or activities.', 'reverse' => false],
            ['text' => 'I get motivated by tracking progress toward a specific outcome.', 'reverse' => false],
            ['text' => 'I often push myself to “level up” in skills or performance.', 'reverse' => false],
            ['text' => 'I feel most satisfied when I hit a benchmark I’ve been chasing.', 'reverse' => false],
            ['text' => 'I like seeing tangible results from my effort.', 'reverse' => false],
            ['text' => 'I’m often asking myself, “What’s the next step to get better?”', 'reverse' => false],
            ['text' => 'I feel uncomfortable when I’m not working toward something.', 'reverse' => false],
            ['text' => 'I take pride in being known as “good at” something.', 'reverse' => false],
            ['text' => 'I don’t care much about proving myself or improving.', 'reverse' => true],
            ['text' => 'I lose interest if there isn’t a clear goal or result to aim for.', 'reverse' => true],
        ],
        'socializer' => [
            ['text' => 'I often learn best through dialogue or conversation.', 'reverse' => false],
            ['text' => 'I feel energized by working with others toward a shared goal.', 'reverse' => false],
            ['text' => 'I value being seen as helpful or supportive.', 'reverse' => false],
            ['text' => 'I build friendships even in settings where I don’t have to.', 'reverse' => false],
            ['text' => 'I often reflect on how my actions affect others.', 'reverse' => false],
            ['text' => 'I’m happiest when I’m contributing to a team or group.', 'reverse' => false],
            ['text' => 'I get insights from feedback or discussion more than solo reflection.', 'reverse' => false],
            ['text' => 'I like collaborating more than competing.', 'reverse' => false],
            ['text' => 'I don’t enjoy group work or social activities.', 'reverse' => true],
            ['text' => 'I’d rather work alone even if teamwork might help me.', 'reverse' => true],
        ],
        'strategist' => [
            ['text' => 'I’m motivated when there’s something (or someone) to beat.', 'reverse' => false],
            ['text' => 'I enjoy high-stakes challenges or pressure-filled environments.', 'reverse' => false],
            ['text' => 'I track how I compare to others in my school, sports, or hobbies.', 'reverse' => false],
            ['text' => 'I feel driven when others underestimate me.', 'reverse' => false],
            ['text' => 'I enjoy debate or structured argument.', 'reverse' => false],
            ['text' => 'I often analyze others’ strategies and look for weaknesses.', 'reverse' => false],
            ['text' => 'I like optimizing performance for maximum results.', 'reverse' => false],
            ['text' => 'I get a thrill from being recognized as the best at something.', 'reverse' => false],
            ['text' => 'I don’t care much about competing or winning.', 'reverse' => true],
            ['text' => 'I avoid challenges where I might lose.', 'reverse' => true],
        ],
    ],
    'graduate' => [
        'explorer' => [
            ['text' => 'I enjoy diving into new systems or tools just to see how they work.', 'reverse' => false],
            ['text' => 'I’d rather explore a new idea than stick with what I already know.', 'reverse' => false],
            ['text' => 'I often get lost in rabbit holes of curiosity.', 'reverse' => false],
            ['text' => 'I try new processes or strategies even when the old ones still work.', 'reverse' => false],
            ['text' => 'I value learning for its own sake.', 'reverse' => false],
            ['text' => 'I enjoy being surprised by something I didn’t expect.', 'reverse' => false],
            ['text' => 'I like being the first to discover something new in my field or hobby.', 'reverse' => false],
            ['text' => 'I often research things deeply even if I don’t need to.', 'reverse' => false],
            ['text' => 'I avoid experimenting if it might lead to mistakes.', 'reverse' => true],
            ['text' => 'I’d rather not explore if it takes me off track.', 'reverse' => true],
        ],
        'achiever' => [
            ['text' => 'I set measurable goals for myself in most areas of life.', 'reverse' => false],
            ['text' => 'I get motivated by tracking progress toward a specific outcome.', 'reverse' => false],
            ['text' => 'I often push myself to “level up” in skills or performance.', 'reverse' => false],
            ['text' => 'I feel most satisfied when I hit a benchmark I’ve been chasing.', 'reverse' => false],
            ['text' => 'I like seeing tangible results from my effort.', 'reverse' => false],
            ['text' => 'I’m often asking myself, “What’s the next step to get better?”', 'reverse' => false],
            ['text' => 'I feel uncomfortable when I’m not working toward something.', 'reverse' => false],
            ['text' => 'I enjoy testing my abilities in structured ways (courses, certifications, etc.).', 'reverse' => false],
            ['text' => 'I don’t care much about setting or achieving goals.', 'reverse' => true],
            ['text' => 'I lose motivation if results aren’t clearly measurable.', 'reverse' => true],
        ],
        'socializer' => [
            ['text' => 'I often learn best through dialogue or conversation.', 'reverse' => false],
            ['text' => 'I feel energized by working with others toward a shared goal.', 'reverse' => false],
            ['text' => 'I value being seen as helpful or supportive.', 'reverse' => false],
            ['text' => 'I build relationships even in settings where I don’t have to.', 'reverse' => false],
            ['text' => 'I often reflect on how my actions affect others.', 'reverse' => false],
            ['text' => 'I’m happiest when I’m contributing to a team or community.', 'reverse' => false],
            ['text' => 'I get insights from feedback or discussion more than solo reflection.', 'reverse' => false],
            ['text' => 'I’m naturally drawn to group projects, coaching, or mentorship.', 'reverse' => false],
            ['text' => 'I don’t get much out of group learning or collaboration.', 'reverse' => true],
            ['text' => 'I’d rather avoid teamwork, even if it could help.', 'reverse' => true],
        ],
        'strategist' => [
            ['text' => 'I’m motivated when there’s something (or someone) to beat.', 'reverse' => false],
            ['text' => 'I enjoy high-stakes challenges or pressure-filled environments.', 'reverse' => false],
            ['text' => 'I track how I compare to others in my field or industry.', 'reverse' => false],
            ['text' => 'I feel driven when others underestimate me.', 'reverse' => false],
            ['text' => 'I enjoy debate or structured argument.', 'reverse' => false],
            ['text' => 'I often analyze others’ strategies and look for weaknesses.', 'reverse' => false],
            ['text' => 'I like optimizing performance for maximum results.', 'reverse' => false],
            ['text' => 'I get a thrill from being recognized as the best at something.', 'reverse' => false],
            ['text' => 'I don’t like competing or comparing myself to others.', 'reverse' => true],
            ['text' => 'I avoid situations where I might not win.', 'reverse' => true],
        ],
    ],
    'adult' => [
        'explorer' => [
            ['text' => 'I enjoy diving into new systems or tools just to see how they work.', 'reverse' => false],
            ['text' => 'I’d rather explore a new idea than stick with what I already know.', 'reverse' => false],
            ['text' => 'I often get lost in rabbit holes of curiosity.', 'reverse' => false],
            ['text' => 'I try new processes or strategies even when the old ones still work.', 'reverse' => false],
            ['text' => 'I value learning for its own sake.', 'reverse' => false],
            ['text' => 'I enjoy being surprised by something I didn’t expect.', 'reverse' => false],
            ['text' => 'I like being the first to discover something new in my field or industry.', 'reverse' => false],
            ['text' => 'I often research things deeply even if I don’t need to.', 'reverse' => false],
            ['text' => 'I avoid experimenting if the outcome is uncertain.', 'reverse' => true],
            ['text' => 'I prefer not to explore if it means leaving proven methods.', 'reverse' => true],
        ],
        'achiever' => [
            ['text' => 'I set measurable goals for myself in most areas of life.', 'reverse' => false],
            ['text' => 'I get motivated by tracking progress toward a specific outcome.', 'reverse' => false],
            ['text' => 'I often push myself to “level up” in skills or performance.', 'reverse' => false],
            ['text' => 'I feel most satisfied when I hit a benchmark I’ve been chasing.', 'reverse' => false],
            ['text' => 'I like seeing tangible results from my effort.', 'reverse' => false],
            ['text' => 'I’m often asking myself, “What’s the next step to get better?”', 'reverse' => false],
            ['text' => 'I feel uncomfortable when I’m not working toward something.', 'reverse' => false],
            ['text' => 'I enjoy testing my abilities in structured ways (courses, certifications, etc.).', 'reverse' => false],
            ['text' => 'I don’t feel the need to prove myself or improve my performance.', 'reverse' => true],
            ['text' => 'I lose motivation if I don’t have a clear outcome to reach.', 'reverse' => true],
        ],
        'socializer' => [
            ['text' => 'I often learn best through dialogue or conversation.', 'reverse' => false],
            ['text' => 'I feel energized by working with others toward a shared goal.', 'reverse' => false],
            ['text' => 'I value being seen as helpful or supportive.', 'reverse' => false],
            ['text' => 'I build relationships even in professional settings where I don’t have to.', 'reverse' => false],
            ['text' => 'I often reflect on how my actions affect others.', 'reverse' => false],
            ['text' => 'I’m happiest when I’m contributing to a team or community.', 'reverse' => false],
            ['text' => 'I get insights from feedback or discussion more than solo reflection.', 'reverse' => false],
            ['text' => 'I’m naturally drawn to group projects, coaching, or mentorship.', 'reverse' => false],
            ['text' => 'I don’t find much value in team-based work.', 'reverse' => true],
            ['text' => 'I’d rather avoid group projects if possible.', 'reverse' => true],
        ],
        'strategist' => [
            ['text' => 'I’m motivated when there’s something (or someone) to beat.', 'reverse' => false],
            ['text' => 'I enjoy high-stakes challenges or pressure-filled environments.', 'reverse' => false],
            ['text' => 'I track how I compare to others in my field or industry.', 'reverse' => false],
            ['text' => 'I feel driven when others underestimate me.', 'reverse' => false],
            ['text' => 'I enjoy debate or structured argument.', 'reverse' => false],
            ['text' => 'I often analyze others’ strategies and look for weaknesses.', 'reverse' => false],
            ['text' => 'I like optimizing performance for maximum results.', 'reverse' => false],
            ['text' => 'I get a thrill from being recognized as the best at something.', 'reverse' => false],
            ['text' => 'I don’t enjoy competing or measuring myself against others.', 'reverse' => true],
            ['text' => 'I avoid high-stakes challenges because I’d rather not risk losing.', 'reverse' => true],
        ],
    ],
];